// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDAHymns.Core.Data;

#nullable disable

namespace SDAHymns.Core.Migrations
{
    [DbContext(typeof(HymnsContext))]
    [Migration("20251226002941_UpdateDisplayProfiles")]
    partial class UpdateDisplayProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SDAHymns.Core.Data.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Last time legacy XML was imported",
                            Key = "LastDatabaseImportDate",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default display profile ID",
                            Key = "DefaultDisplayProfileId",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Track hymn usage statistics",
                            Key = "EnableStatisticsTracking",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        });
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.AudioRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultPlaybackSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HymnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecordingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tempo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("HymnId");

                    b.ToTable("AudioRecordings");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.DisplayProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImageMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("BackgroundImageOpacity")
                        .HasColumnType("REAL");

                    b.Property<string>("BackgroundImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("BackgroundOpacity")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableTextOutline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableTextShadow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FontWeight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemProfile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("LabelFontSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LetterSpacing")
                        .HasColumnType("REAL");

                    b.Property<double>("LineHeight")
                        .HasColumnType("REAL");

                    b.Property<int>("MarginBottom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginRight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginTop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutlineColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutlineThickness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShadowBlurRadius")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShadowColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShadowOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShadowOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowHymnTitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowVerseNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextAlignment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleFontSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TransparentBackground")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerseFontSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerticalAlignment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DisplayProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = "#0078D4",
                            BackgroundColor = "#000000",
                            BackgroundImageMode = "Fill",
                            BackgroundImageOpacity = 0.29999999999999999,
                            BackgroundOpacity = 1.0,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default black background with white text, left-aligned",
                            EnableTextOutline = false,
                            EnableTextShadow = false,
                            FontFamily = "Inter",
                            FontWeight = "Normal",
                            IsDefault = true,
                            IsSystemProfile = true,
                            LabelColor = "#CCCCCC",
                            LabelFontSize = 28,
                            LetterSpacing = 0.0,
                            LineHeight = 1.3999999999999999,
                            MarginBottom = 60,
                            MarginLeft = 100,
                            MarginRight = 100,
                            MarginTop = 60,
                            Name = "Classic Dark",
                            OutlineColor = "#000000",
                            OutlineThickness = 2,
                            ShadowBlurRadius = 10,
                            ShadowColor = "#000000",
                            ShadowOffsetX = 2,
                            ShadowOffsetY = 2,
                            ShowHymnTitle = true,
                            ShowVerseNumbers = true,
                            TextAlignment = "Left",
                            TextColor = "#FFFFFF",
                            TitleColor = "#FFFFFF",
                            TitleFontSize = 36,
                            TransparentBackground = false,
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerseFontSize = 48,
                            VerticalAlignment = "Center"
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = "#FFFFFF",
                            BackgroundColor = "#000000",
                            BackgroundImageMode = "Fill",
                            BackgroundImageOpacity = 0.29999999999999999,
                            BackgroundOpacity = 1.0,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pure black and white with bold text and shadow for maximum visibility",
                            EnableTextOutline = false,
                            EnableTextShadow = true,
                            FontFamily = "Inter",
                            FontWeight = "Bold",
                            IsDefault = false,
                            IsSystemProfile = true,
                            LabelColor = "#FFFFFF",
                            LabelFontSize = 32,
                            LetterSpacing = 0.0,
                            LineHeight = 1.3999999999999999,
                            MarginBottom = 60,
                            MarginLeft = 100,
                            MarginRight = 100,
                            MarginTop = 60,
                            Name = "High Contrast",
                            OutlineColor = "#000000",
                            OutlineThickness = 2,
                            ShadowBlurRadius = 15,
                            ShadowColor = "#000000",
                            ShadowOffsetX = 3,
                            ShadowOffsetY = 3,
                            ShowHymnTitle = true,
                            ShowVerseNumbers = true,
                            TextAlignment = "Left",
                            TextColor = "#FFFFFF",
                            TitleColor = "#FFFFFF",
                            TitleFontSize = 40,
                            TransparentBackground = false,
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerseFontSize = 56,
                            VerticalAlignment = "Center"
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = "#0078D4",
                            BackgroundColor = "#000000",
                            BackgroundImageMode = "Fill",
                            BackgroundImageOpacity = 0.29999999999999999,
                            BackgroundOpacity = 0.0,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transparent background with text outline for streaming over video",
                            EnableTextOutline = true,
                            EnableTextShadow = false,
                            FontFamily = "Inter",
                            FontWeight = "SemiBold",
                            IsDefault = false,
                            IsSystemProfile = true,
                            LabelColor = "#EEEEEE",
                            LabelFontSize = 30,
                            LetterSpacing = 0.0,
                            LineHeight = 1.3999999999999999,
                            MarginBottom = 80,
                            MarginLeft = 120,
                            MarginRight = 120,
                            MarginTop = 80,
                            Name = "OBS Stream",
                            OutlineColor = "#000000",
                            OutlineThickness = 3,
                            ShadowBlurRadius = 10,
                            ShadowColor = "#000000",
                            ShadowOffsetX = 2,
                            ShadowOffsetY = 2,
                            ShowHymnTitle = true,
                            ShowVerseNumbers = true,
                            TextAlignment = "Center",
                            TextColor = "#FFFFFF",
                            TitleColor = "#FFFFFF",
                            TitleFontSize = 40,
                            TransparentBackground = true,
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerseFontSize = 52,
                            VerticalAlignment = "Center"
                        },
                        new
                        {
                            Id = 4,
                            AccentColor = "#FFD700",
                            BackgroundColor = "#001F3F",
                            BackgroundImageMode = "Fill",
                            BackgroundImageOpacity = 0.29999999999999999,
                            BackgroundOpacity = 1.0,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dark blue background with yellow text for bright environments",
                            EnableTextOutline = false,
                            EnableTextShadow = true,
                            FontFamily = "Inter",
                            FontWeight = "Bold",
                            IsDefault = false,
                            IsSystemProfile = true,
                            LabelColor = "#FFC700",
                            LabelFontSize = 30,
                            LetterSpacing = 0.0,
                            LineHeight = 1.3999999999999999,
                            MarginBottom = 60,
                            MarginLeft = 100,
                            MarginRight = 100,
                            MarginTop = 60,
                            Name = "Bright Room",
                            OutlineColor = "#000000",
                            OutlineThickness = 2,
                            ShadowBlurRadius = 12,
                            ShadowColor = "#000000",
                            ShadowOffsetX = 2,
                            ShadowOffsetY = 2,
                            ShowHymnTitle = true,
                            ShowVerseNumbers = true,
                            TextAlignment = "Center",
                            TextColor = "#FFD700",
                            TitleColor = "#FFD700",
                            TitleFontSize = 38,
                            TransparentBackground = false,
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerseFontSize = 52,
                            VerticalAlignment = "Center"
                        },
                        new
                        {
                            Id = 5,
                            AccentColor = "#666666",
                            BackgroundColor = "#000000",
                            BackgroundImageMode = "Fill",
                            BackgroundImageOpacity = 0.29999999999999999,
                            BackgroundOpacity = 1.0,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clean and simple with minimal styling",
                            EnableTextOutline = false,
                            EnableTextShadow = false,
                            FontFamily = "Inter",
                            FontWeight = "Normal",
                            IsDefault = false,
                            IsSystemProfile = true,
                            LabelColor = "#CCCCCC",
                            LabelFontSize = 26,
                            LetterSpacing = 0.0,
                            LineHeight = 1.5,
                            MarginBottom = 50,
                            MarginLeft = 80,
                            MarginRight = 80,
                            MarginTop = 50,
                            Name = "Minimalist",
                            OutlineColor = "#000000",
                            OutlineThickness = 2,
                            ShadowBlurRadius = 10,
                            ShadowColor = "#000000",
                            ShadowOffsetX = 2,
                            ShadowOffsetY = 2,
                            ShowHymnTitle = true,
                            ShowVerseNumbers = true,
                            TextAlignment = "Left",
                            TextColor = "#EEEEEE",
                            TitleColor = "#EEEEEE",
                            TitleFontSize = 32,
                            TransparentBackground = false,
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerseFontSize = 44,
                            VerticalAlignment = "Center"
                        },
                        new
                        {
                            Id = 6,
                            AccentColor = "#D4AF37",
                            BackgroundColor = "#00274D",
                            BackgroundImageMode = "Fill",
                            BackgroundImageOpacity = 0.29999999999999999,
                            BackgroundOpacity = 1.0,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic church aesthetic with navy and gold colors",
                            EnableTextOutline = false,
                            EnableTextShadow = false,
                            FontFamily = "Georgia",
                            FontWeight = "Normal",
                            IsDefault = false,
                            IsSystemProfile = true,
                            LabelColor = "#C4A030",
                            LabelFontSize = 32,
                            LetterSpacing = 0.0,
                            LineHeight = 1.5,
                            MarginBottom = 70,
                            MarginLeft = 120,
                            MarginRight = 120,
                            MarginTop = 70,
                            Name = "Traditional",
                            OutlineColor = "#000000",
                            OutlineThickness = 2,
                            ShadowBlurRadius = 10,
                            ShadowColor = "#000000",
                            ShadowOffsetX = 2,
                            ShadowOffsetY = 2,
                            ShowHymnTitle = true,
                            ShowVerseNumbers = true,
                            TextAlignment = "Center",
                            TextColor = "#D4AF37",
                            TitleColor = "#D4AF37",
                            TitleFontSize = 40,
                            TransparentBackground = false,
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerseFontSize = 50,
                            VerticalAlignment = "Center"
                        });
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.Hymn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyPowerPointPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Number");

                    b.HasIndex("Title");

                    b.HasIndex("Number", "CategoryId")
                        .IsUnique();

                    b.ToTable("Hymns");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.HymnCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyFolderPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("HymnCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Main Christian hymnbook",
                            DisplayOrder = 1,
                            LegacyFolderPath = "Imnuri Azs/Resurse/Imnuri crestine",
                            Name = "Imnuri crestine",
                            Slug = "crestine",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pathfinder/Companion hymns",
                            DisplayOrder = 2,
                            LegacyFolderPath = "Imnuri Azs/Resurse/Imnuri companioni",
                            Name = "Imnuri companioni",
                            Slug = "companioni",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explorer hymns",
                            DisplayOrder = 3,
                            LegacyFolderPath = "Imnuri Azs/Resurse/Imnuri exploratori",
                            Name = "Imnuri exploratori",
                            Slug = "exploratori",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Firefly hymns (children's songs)",
                            DisplayOrder = 4,
                            LegacyFolderPath = "Imnuri Azs/Resurse/Imnuri licurici",
                            Name = "Imnuri licurici",
                            Slug = "licurici",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Youth hymns",
                            DisplayOrder = 5,
                            LegacyFolderPath = "Imnuri Azs/Resurse/Imnuri tineret",
                            Name = "Imnuri tineret",
                            Slug = "tineret",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.ServicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("ServiceDate");

                    b.ToTable("ServicePlans");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.ServicePlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HymnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedVerses")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicePlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HymnId");

                    b.HasIndex("ServicePlanId", "DisplayOrder");

                    b.ToTable("ServicePlanItems");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.UsageStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AudioPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HymnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServicePlanName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HymnId");

                    b.HasIndex("UsedAt");

                    b.ToTable("UsageStatistics");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HymnId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsContinuation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HymnId");

                    b.HasIndex("HymnId", "DisplayOrder");

                    b.HasIndex("HymnId", "VerseNumber")
                        .IsUnique();

                    b.ToTable("Verses");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.AudioRecording", b =>
                {
                    b.HasOne("SDAHymns.Core.Data.Models.Hymn", "Hymn")
                        .WithMany("AudioRecordings")
                        .HasForeignKey("HymnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hymn");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.Hymn", b =>
                {
                    b.HasOne("SDAHymns.Core.Data.Models.HymnCategory", "Category")
                        .WithMany("Hymns")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.ServicePlanItem", b =>
                {
                    b.HasOne("SDAHymns.Core.Data.Models.Hymn", "Hymn")
                        .WithMany("ServicePlanItems")
                        .HasForeignKey("HymnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDAHymns.Core.Data.Models.ServicePlan", "ServicePlan")
                        .WithMany("Items")
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hymn");

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.UsageStatistic", b =>
                {
                    b.HasOne("SDAHymns.Core.Data.Models.Hymn", "Hymn")
                        .WithMany("UsageStatistics")
                        .HasForeignKey("HymnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hymn");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.Verse", b =>
                {
                    b.HasOne("SDAHymns.Core.Data.Models.Hymn", "Hymn")
                        .WithMany("Verses")
                        .HasForeignKey("HymnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hymn");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.Hymn", b =>
                {
                    b.Navigation("AudioRecordings");

                    b.Navigation("ServicePlanItems");

                    b.Navigation("UsageStatistics");

                    b.Navigation("Verses");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.HymnCategory", b =>
                {
                    b.Navigation("Hymns");
                });

            modelBuilder.Entity("SDAHymns.Core.Data.Models.ServicePlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
